### ISSUE TITLE
Проигрывать с...

### ISSUE THREAD

**Issue by wheredevel** [afedchin/xbmctorrent#13]
Для сезонов сериалов с сериями: 

Раньше каждый эпизод в сезоне помечался галочкой, если просмотрен.
Теперь - есть список эпизодов БЕЗ галочек.
И без возможности менять вид списка (узкий).

Раньше конкретную серию можно было "смотреть с..."
Теперь - "смотреть с..." показывается на весь сезон. 
И, если его выбрать - не работает. Проигрывание останавливается.
А если выбрать "проигрывать сначала", то работает. Только эпизод идет сначала.

**Comment by afedchin** [comment]
про что конкретно едёт речь LF, rutor, rutracker?

**Comment by wheredevel** [comment]
rutor

**Comment by afedchin** [comment]
now it's a default behavior.

**Comment by wheredevel** [comment]
Но ведь это бесполезно для пользователя, если сравнивать с прошлыми версиями...

**Comment by afedchin** [comment]
это работло хорошо только с торрентами у которых несколько файлов (таких как сералы), но вызывало другие проблемы с другими раздачами. текущее решение - компромис.
